### PR TITLE
feat: Add commands for inserting markdown alert blocks

### PR DESCRIPTION
**Pull request by rafistrauss**
Adds commands to the command palette for quickly inserting the tip markdown

### CODE REVIEW

**Review by kylebutts — APPROVED** [review]
thanks!

**Comment by rafistrauss** [comment]
> thanks!

Thank you for creating the extension 😄

**Comment by rafistrauss** [comment]
@kylebutts any chance you're planning on merging & publishing? 😅

**Comment by kylebutts** [comment]
@rafistrauss sorry, thanks for the ping! The mdit-plugins now has alert support, so probably no need to publish this extension: https://mdit-plugins.github.io/alert.html

**Pull request merged**
